
import { ArtistProfile } from '../types/index.ts';

export const artistProfiles: ArtistProfile[] = [
  {
    artist: "Tabou Combo",
    fullName: "Tabou Combo de Pétion-Ville",
    origin: "Pétion-Ville, Haiti",
    genre: "Konpa, World music",
    overview: "One of the most legendary and influential Haitian Konpa bands, Tabou Combo has been a global ambassador for the genre since its formation in 1968. Known for their infectious rhythms, powerful horn section, and socially conscious lyrics, they've produced timeless hits like 'New York City' and 'Juicy Lucy'.",
    popularSongs: ["New York City", "Juicy Lucy", "Mabouya", "Zap Zap", "Aux Antilles"],
    imageUrl: "https://i.scdn.co/image/ab6761610000e5eb5d6a8b0a5b2a0c2e0a2d3c1e",
  },
  {
    artist: "Skah-Shah #1",
    origin: "Port-au-Prince, Haiti",
    genre: "Konpa",
    overview: "Formed in the early 1970s, Skah-Shah #1 quickly became a powerhouse in the Konpa scene with their sophisticated arrangements and romantic ballads. Their music defined an era of Haitian music and continues to be celebrated for its elegance and emotional depth.",
    popularSongs: ["Caroline", "Ozanana", "Synthese Musicale", "Men Nimewo A"],
    imageUrl: "https://i.ytimg.com/vi/y-mQ2Hn2j-s/maxresdefault.jpg",
  },
  {
    artist: "D.P. Express",
    origin: "Port-au-Prince, Haiti",
    genre: "Konpa",
    overview: "Led by Ti Manno, D.P. Express was known for its powerful horn section and energetic performances. Their music often touched on social and political issues, making them a significant voice in Haiti during the 1970s and 80s. Their hit 'David' remains an iconic Konpa anthem.",
    popularSongs: ["David", "La Vie", "Reflechi", "M'pa Pran Kontak", "Bariè"],
    imageUrl: "https://www.radiotelevisioncaraibes.com/wp-content/uploads/2021/04/DP-Express.jpg",
  },
  {
    artist: "Les Frères Déjean",
    fullName: "Les Frères Déjean de Pétion-Ville",
    origin: "Pétion-Ville, Haiti",
    genre: "Konpa",
    overview: "A family band that became one of the pillars of Konpa music. Les Frères Déjean are celebrated for their polished sound, intricate horn arrangements, and classic hits that have become standards of the genre. Their music is synonymous with class and musical excellence.",
    popularSongs: ["Belle Deesse", "L'Univers", "Marina", "Pa Gain Panne", "Haiti"],
    imageUrl: "https://i.ytimg.com/vi/XbJc8mB_Hn4/hqdefault.jpg",
  },
  {
    artist: "Magnum Band",
    origin: "Port-au-Prince, Haiti",
    genre: "Konpa, Racine",
    overview: "Fronted by the legendary Dadou Pasquet, Magnum Band is known for its unique fusion of Konpa with rock, jazz, and traditional Haitian Vodou rhythms. Their sound is powerful, innovative, and deeply rooted in Haitian culture, making them one of the most respected bands in the industry.",
    popularSongs: ["Adoration", "Paka Pala", "Liberté", "Fierté", "Experience"],
    imageUrl: "https://i1.sndcdn.com/artworks-000171221718-i6u3sl-t500x500.jpg",
  },
  {
    artist: "System Band",
    origin: "New York, USA",
    genre: "Konpa direk",
    overview: "Formed in the Haitian diaspora of New York City, System Band quickly became a dominant force in the Konpa scene. With their energetic performances and a string of hits, they have maintained their status as one of the most popular and enduring Konpa bands for decades.",
    popularSongs: ["Ou Trompé'm", "Anita", "Chagrin D'amour", "Beeper", "Vacances"],
    imageUrl: "https://f4.bcbits.com/img/a1953259832_10.jpg",
  },
  {
    artist: "Orchestre Tropicana d'Haïti",
    origin: "Cap-Haïtien, Haiti",
    genre: "Konpa, Big band",
    overview: "Known as 'The Rocket of the North', Orchestre Tropicana d'Haïti is a legendary big band from Cap-Haïtien. For over 50 years, they have been a cultural institution, celebrated for their lush arrangements, timeless boleros, and classic Konpa sound that represents the pride of Northern Haiti.",
    popularSongs: ["Ti Jocelyne", "Serenade Des Melomanes", "Frè Koté Papa", "24 Décembre"],
    imageUrl: "https://i.scdn.co/image/ab67616d0000b273523287600609a341e3a95d73",
  },
  {
    artist: "Coupé Cloué",
    fullName: "Gesner Jean-Henri",
    born: "May 10, 1925",
    origin: "Léogâne, Haiti",
    genre: "Konpa manba",
    overview: "Known as 'Roi Coupé', Coupé Cloué was a true Haitian icon. He created his own style, 'Konpa manba', characterized by his spoken, storytelling delivery over a relaxed guitar-driven rhythm. His lyrics, often full of humor and social commentary, made him one of Haiti's most beloved and unique artists.",
    popularSongs: ["Myan Myan", "Fanm Kolokent", "Juge'm Byen", "Madan Marcel"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/2/2f/Coupe_cloue.jpg",
  },
  {
    artist: "Zenglen",
    origin: "Miami, USA",
    genre: "Konpa",
    overview: "A cornerstone of the 'Nouvelle Génération' Konpa scene, Zenglen has been a dominant force for over three decades. Known for their sophisticated arrangements, heartfelt lyrics, and ability to constantly reinvent their sound, they have produced countless hits and launched the careers of many famous singers.",
    popularSongs: ["5 Dwet", "Tempo", "Sexy Love", "Let it Groove", "Rezilta"],
    imageUrl: "https://i.scdn.co/image/ab6761610000e5eb1d36d4007b8b4081c7e90956",
  },
  {
    artist: "Carimi",
    origin: "New York, USA",
    genre: "Konpa",
    overview: "Carimi exploded onto the scene in the early 2000s and quickly became one of the most popular bands of their generation. Their energetic, pop-infused Konpa, combined with electrifying stage performances, earned them a massive following worldwide until their separation in 2016.",
    popularSongs: ["Ayiti Bang Bang", "Buzz", "I'm a Freak", "Kita Nago"],
    imageUrl: "https://e.snmc.io/i/600/s/13a07851e22384a274ffca0b7d7f2674/4134988",
  },
  {
    artist: "Roody Roodboy",
    fullName: "Roody Pétuel Dauphin",
    born: "June 27, 1988",
    origin: "Haiti",
    genre: "Hip-Hop",
    overview: "Roody Roodboy is a leading figure in Haitian hip-hop, known for his energetic delivery and socially engaged lyrics. He discovered his passion for music in 2005 and has since built a major following with both powerful singles and full-length albums.",
    popularSongs: [
      "Lobey (2017)",
      "Tranble (2017)",
      "Fo Fim Kap Fèt (2021)",
      "Dous Pou Dous (2023)",
      "Sorry to My Ex (2023)",
      "Men Manmi Tololo (2023)",
    ],
    following: [
      { platform: "YouTube", count: "1M+ subscribers" },
      { platform: "Instagram", count: "1.8M+ followers" },
      { platform: "X (Twitter)", count: "Active" }
    ],
    links: [
      { platform: "YouTube", url: "https://www.youtube.com/@RoodyRoodboy" },
      { platform: "Spotify", url: "https://open.spotify.com/artist" },
      { platform: "Instagram", url: "https://www.instagram.com/roodyroodboyhaiti" },
      { platform: "X (Twitter)", url: "https://x.com/roodyroodboy" }
    ],
    imageUrl: "/assets/roodyroodboy.jpg",
  },
];